# -*- coding: utf-8 -*-
"""taskwise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvHKK8Tt38p1Sb7hQGwnYv1FpfQckIzL

# CCS3440_AI-Final-Assignment_Group-02

# Option C: Disease Risk Classification - SmartCare Hospital

# Task 03 – Data Preprocessing and Feature Engineering

## Mount Drive & Load Data
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# change this path to wherever you put your files in Drive
folder = '/content/drive/MyDrive/SmartCare/'

df = pd.read_csv(folder + 'smartcare_ai_dataset_1000.csv')
data_dict = pd.read_csv(folder + 'smartcare_ai_dataset_data_dictionary.csv')

print(df.shape)
df.head()

# Missing Values Handling
df.isnull().sum()[df.isnull().sum() > 0]

pd.crosstab(df['admitted'], df['room_type'].isnull())

df_clean = df.copy()

# admitted=0 -> genuinely "no room", meaningful category
df_clean.loc[df_clean['admitted'] == 0, 'room_type'] = \
    df_clean.loc[df_clean['admitted'] == 0, 'room_type'].fillna('Not Admitted')

# admitted=1 but still missing -> real data gap, fill with most common room type
mode_room = df_clean.loc[df_clean['admitted'] == 1, 'room_type'].mode()[0]
df_clean.loc[df_clean['admitted'] == 1, 'room_type'] = \
    df_clean.loc[df_clean['admitted'] == 1, 'room_type'].fillna(mode_room)

print("Remaining missing values:", df_clean['room_type'].isnull().sum())
print(df_clean['room_type'].value_counts())

# Duplicate Record Detection
full_row_dupes = df.duplicated().sum()
patient_id_dupes = df['patient_id'].duplicated().sum()
record_id_dupes = df['record_id'].duplicated().sum()

print(f"Fully duplicated rows        : {full_row_dupes}")
print(f"Duplicated patient_id values : {patient_id_dupes}")
print(f"Duplicated record_id values  : {record_id_dupes}")

df_clean = df_clean.drop_duplicates()

# Outlier identificatio (IQR method)
numeric_cols = ['age','bmi','systolic_bp','diastolic_bp','blood_sugar_mg_dl','cholesterol_mg_dl','total_bill_lkr']

for col in numeric_cols:
    Q1, Q3 = df_clean[col].quantile([0.25, 0.75])
    IQR = Q3 - Q1
    lower, upper = Q1 - 1.5*IQR, Q3 + 1.5*IQR
    outliers = df_clean[(df_clean[col] < lower) | (df_clean[col] > upper)]
    print(f"{col}: {len(outliers)} outliers")

# Feature Engineering
df_feat = df_clean.copy()

df_feat['appointment_date'] = pd.to_datetime(df_feat['appointment_date'])

# Age group — standard clinical age bands
df_feat['age_group'] = pd.cut(
    df_feat['age'], bins=[0, 17, 35, 50, 65, 120],
    labels=['Under 18', '18-35', '36-50', '51-65', '65+']
)

# BMI category — WHO standard cutoffs
df_feat['bmi_category'] = pd.cut(
    df_feat['bmi'], bins=[0, 18.5, 25, 30, 100],
    labels=['Underweight', 'Normal', 'Overweight', 'Obese']
)

# Blood pressure category — clinical staging (systolic-led)
def bp_category(row):
    s, d = row['systolic_bp'], row['diastolic_bp']
    if s < 120 and d < 80:
        return 'Normal'
    elif s < 130 and d < 80:
        return 'Elevated'
    else:
        return 'Stage 1 Hypertension'
df_feat['bp_category'] = df_feat.apply(bp_category, axis=1)

# Missed-appointment rate (guard against divide-by-zero)
df_feat['missed_appointment_rate'] = np.where(
    df_feat['previous_appointments'] > 0,
    df_feat['missed_previous_appointments'] / df_feat['previous_appointments'],
    0.0
)

# Chronic-patient flag — repeat admissions signal a chronic condition
df_feat['is_chronic_patient'] = (df_feat['previous_admissions'] >= 2).astype(int)

# Care intensity — combined labs + treatments in this visit
df_feat['care_intensity'] = df_feat['lab_tests_count'] + df_feat['treatments_count']

# Appointment seasonality
df_feat['appointment_month'] = df_feat['appointment_date'].dt.month
df_feat['appointment_quarter'] = df_feat['appointment_date'].dt.quarter

# Convert pd.cut Categorical outputs to plain strings (needed before encoding)
df_feat['age_group'] = df_feat['age_group'].astype(str)
df_feat['bmi_category'] = df_feat['bmi_category'].astype(str)

print("Shape after feature engineering:", df_feat.shape)
df_feat.head()

# Data Cleaning - drop irrelevant / leakage columns
drop_cols = ['record_id', 'patient_id', 'appointment_date', 'no_show', 'readmitted_30_days']
df_model = df_feat.drop(columns=drop_cols)   # built from df_feat (keeps engineered features)

print("Shape after cleaning:", df_model.shape)

# Save cleaned dataset (once — human-readable, before encoding)

df_feat.to_csv(folder + 'smartcare_cleaned.csv', index=False)
print("Saved:", folder + 'smartcare_cleaned.csv', df_feat.shape)

from google.colab import files
files.download(folder + 'smartcare_cleaned.csv')

# Feature Encoding
from sklearn.preprocessing import LabelEncoder

categorical_cols = df_model.select_dtypes(include='object').columns.tolist()
categorical_cols.remove('disease_risk_level')  # keep target separate for now
print("Categorical columns to encode:", categorical_cols)

encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df_model[col] = le.fit_transform(df_model[col])
    encoders[col] = le

# Encode target (Low/Medium/High -> numbers)
target_encoder = LabelEncoder()
df_model['disease_risk_level'] = target_encoder.fit_transform(df_model['disease_risk_level'])
print("Target classes:", list(target_encoder.classes_))

# Feature Selection
from sklearn.feature_selection import SelectKBest, f_classif

X = df_model.drop(columns=['disease_risk_level'])
y = df_model['disease_risk_level']

selector = SelectKBest(score_func=f_classif, k=15)
selector.fit(X, y)

scores = pd.DataFrame({'feature': X.columns, 'score': selector.scores_}).sort_values('score', ascending=False)
print(scores)

selected_features = scores['feature'].head(15).tolist()
print("\nSelected features:", selected_features)

X_selected = X[selected_features]

# Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X_selected), columns=X_selected.columns)

X_scaled.head()

# TRAIN/TEST SPLIT (model-ready data for Task 05)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42, stratify=y
)

print("Train size:", X_train.shape, "Test size:", X_test.shape)

X_train.to_csv(folder + 'X_train.csv', index=False)
X_test.to_csv(folder + 'X_test.csv', index=False)
y_train.to_csv(folder + 'y_train.csv', index=False)
y_test.to_csv(folder + 'y_test.csv', index=False)

print("Saved to Drive:", folder)

from google.colab import files
files.download(folder + 'X_train.csv')
files.download(folder + 'X_test.csv')
files.download(folder + 'y_train.csv')
files.download(folder + 'y_test.csv')